set nocompatible
set incsearch
set ignorecase
set wildmenu
set ruler
set noswapfile
set viewoptions=cursor
set cscopetag
set textwidth=79
set colorcolumn=80,120
set cursorline
set fileencodings=utf-8,ucs-bom,gbk,gb2312,big5,latin1
set backspace=indent,eol,start
"set cindent
set tabstop=8
set softtabstop=8
set shiftwidth=4
"set expandtab
set hls
set encoding=utf-8
set listchars=tab:>-,trail:-
set cinoptions=t0,g1,h1,N-s,j1
set smarttab
set nowrap
set number
set hlsearch
set formatoptions=tcqlron
set foldmethod=syntax
set nofoldenable
set noexpandtab
set tabstop=8
set shiftwidth=8
set cc=120
"set list
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

colorscheme desert
syntax enable
filetype off
filetype plugin indent on

au BufWinLeave ?* mkview
au VimEnter ?* silent loadview
au BufRead,BufNewFile *.testsuite* setfiletype xml
highlight ExtraWhitespace ctermbg=red guibg=red
highlight overlength ctermbg=red ctermfg=white guibg=#592929
match overlength /\%80v.\+/

match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches() " for performance

if has("cscope")
set cscopetag
set csprg=/usr/bin/cscope
"set csprg=/usr/local/bin/cscope
set csto=0
set cst
set nocsverb
if filereadable("cscope.out")
cs add cscope.out
elseif $CSCOPE_DB != ""
cs add $CSCOPE_DB
endif
set csverb
endif

nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>f :cs find f <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>d :cs find d <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR>

imap <silent> <leader>so Signed-off-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>to Tested-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>rc Reviewed-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>rc Reviewed-by: Like Xu <like.xu@linux.intel.com><Esc>

" curl -fLo ~/.vim/autoload/plug.vim --create-dirs 
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" vim +PlugInstall +qall

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-surround'
Plug 'vim-scripts/c.vim'
Plug 'vim-scripts/a.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
"Plug 'fatih/vim-go'
"Plug 'jnwhiteh/vim-golang'
"Plug 'rust-lang/rust.vim'
Plug 'Yggdroot/indentLine'
Plug 'itchyny/lightline.vim'
Plug 'morhetz/gruvbox'
Plug 'ayu-theme/ayu-vim'
Plug 'drewtempelmeyer/palenight.vim'
"Plug 'joshdick/onedark.vim'
Plug 'vim-airline/vim-airline'
Plug 'godlygeek/tabular'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'Raimondi/delimitMate'
Plug 'airblade/vim-gitgutter'
Plug 'TaDaa/vimade'
Plug 'liuchengxu/vista.vim'

call plug#end()

" IRC: #vim-china
" VIM table editor
" vimtex
" https://github.com/wsdjeg/vim-galore-zh_cn
" https://github.com/shime/vim-livedown
" https://github.com/shiracamus/vim-syntax-x86-objdump-d
" https://github.com/yangyangwithgnu/use_vim_as_ide/blob/master/.vimrc

nmap <F2> :NERDTreeToggle<CR>
let NERDTreeWinSize=22
let NERDTreeShowHidden=1
let NERDTreeMinimalUI=1
let NERDTreeAutoDeleteBuffer=1

nmap <F1> :TagbarToggle<CR>

let g:tagbar_width=35
let g:tagbar_autofocus=1
let g:tagbar_right = 1
