set nocompatible
set incsearch
set ignorecase
set wildmenu
set ruler
set nobackup
set noswapfile
set viewoptions=cursor
set cscopetag
set textwidth=79
set colorcolumn=80,120
set cursorline
set showcmd
set fileencodings=utf-8,chinese,latin-1,gb18030,ucs-bom,gbk,gb2312,big5
set backspace=indent,eol,start
"set cindent
set autoindent
set tabstop=4
set softtabstop=8
set shiftwidth=4
"set expandtab
set noexpandtab
set hls
set encoding=utf-8
set listchars=tab:>-,trail:-
set cinoptions=t0,g1,h1,N-s,j1
set smarttab
set nowrap
set number
set hlsearch
set formatoptions=tcqlron
set foldmethod=syntax
set nofoldenable
set tabstop=8
set shiftwidth=8
set cc=120
"set list
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set mouse=n
set history=1024

":version
":edit filename
"vim one.c two.c three.c
":next :wnext :next!
":args
":previous
":wprevious :previous!
"CTRL-^
":split CTRL-W w
":close :only
":split two.c
":new
"CTRL-W +/-
":resize +N
":vsplit two.c
":vertical resize +50
":vnew
":qall quit all windows
":wall     write all windows
":wqall    write and quit all windows
":qall!    quit all windows discard all changes

":tab split
"gt               Go to the next Tab page
"{count}gt        Go to tab page {count}.  The first tab page has number one.
"gT               Go to the previous Tab page
" http://vimdoc.sourceforge.net/htmldoc/tabpage.html#tab-page

":mksession ~/.vim/sessions/tmp.vim
":source ~/.vim/sessions/tmp.vim
":h startify
":h startify-faq
":SLoad       load a session    |startify-:SLoad|
":SSave[!]    save a session    |startify-:SSave|
":SDelete[!]  delete a session  |startify-:SDelete|
":SClose      close a session   |startify-:SClose|

"CTRL-W h	move to the window on the left
"CTRL-W j	move to the window below
"CTRL-W k	move to the window above
"CTRL-W l	move to the window on the right
"CTRL-W t	move to the TOP window
"CTRL-W b	move to the BOTTOM window

colorscheme desert
syntax enable
filetype off
filetype plugin indent on

au BufWinLeave ?* mkview
au VimEnter ?* silent loadview
au BufRead,BufNewFile *.testsuite* setfiletype xml
highlight ExtraWhitespace ctermbg=red guibg=red
highlight overlength ctermbg=red ctermfg=white guibg=#592929
match overlength /\%80v.\+/

match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches() " for performance

if has("cscope")
set cscopetag
"set csprg=/usr/bin/cscope
set csprg=/usr/local/bin/cscope
set csto=0
set cst
set nocsverb
if filereadable("cscope.out")
cs add cscope.out
elseif $CSCOPE_DB != ""
cs add $CSCOPE_DB
endif
set csverb
endif

nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>f :cs find f <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>d :cs find d <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR>

imap <silent> <leader>so Signed-off-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>to Tested-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>rc Reviewed-by: Like Xu <like.xu@linux.intel.com><Esc>
imap <silent> <leader>rc Reviewed-by: Like Xu <like.xu@linux.intel.com><Esc>

" curl -fLo ~/.vim/autoload/plug.vim --create-dirs 
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" vim +PlugInstall +qall

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-surround'
Plug 'vim-scripts/c.vim'
Plug 'vim-scripts/a.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
"Plug 'fatih/vim-go'
"Plug 'jnwhiteh/vim-golang'
"Plug 'rust-lang/rust.vim'
Plug 'Yggdroot/indentLine'
Plug 'itchyny/lightline.vim'
Plug 'morhetz/gruvbox'
Plug 'ayu-theme/ayu-vim'
Plug 'drewtempelmeyer/palenight.vim'
"Plug 'joshdick/onedark.vim'
Plug 'vim-airline/vim-airline'
Plug 'godlygeek/tabular'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'majutsushi/tagbar'
Plug 'Raimondi/delimitMate'
Plug 'airblade/vim-gitgutter'
Plug 'TaDaa/vimade'
Plug 'liuchengxu/vista.vim'
Plug 'ternjs/tern_for_vim'
Plug 'mhinz/vim-startify'

call plug#end()

" IRC: #vim-china
" VIM table editor
" vimtex
" https://github.com/wsdjeg/vim-galore-zh_cn
" https://github.com/shime/vim-livedown
" https://github.com/shiracamus/vim-syntax-x86-objdump-d
" https://github.com/yangyangwithgnu/use_vim_as_ide/blob/master/.vimrc
" http://feihu.me/blog/2014/intro-to-vim/
" https://www.v2ex.com/t/323860

"vim -o file1 file2 ...
"vim -O file1 file2 ...

nmap <F3> :tab split <CR>
nmap <F2> :NERDTreeToggle<CR>
nmap <F1> :TagbarToggle<CR>

autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

:let g:NERDTreeWinSize=30
let g:tagbar_width=115
let g:tagbar_autofocus=1
let g:tagbar_right = 1
